#!/usr/bin/env bash
set -euo pipefail

# Golden Path (dev): local python run with safe defaults.
# - No public exposure: Tailscale mode allowlists requests.
# - Prints local + tailnet URL instructions.

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

export PYTHONUNBUFFERED=1
export STRICT_SECRETS=1

PY="${PYTHON:-}"
if [[ -z "${PY}" ]]; then
  if command -v python3 >/dev/null 2>&1; then PY="python3"; else PY="python"; fi
fi

need_cmd() {
  local c="$1"
  if ! command -v "$c" >/dev/null 2>&1; then
    echo "ERROR: missing prerequisite: $c"
    return 1
  fi
  return 0
}

ensure_env_file() {
  local file="$1"
  local example="$2"
  if [[ -f "$file" ]]; then
    return 0
  fi
  if [[ -f "$example" ]]; then
    cp "$example" "$file"
    echo "Created $file from $example"
    return 0
  fi
  echo "ERROR: missing $file (and template $example not found)"
  return 1
}

ensure_secrets_file() {
  local file=".env.secrets"
  if [[ -f "$file" ]]; then
    # refuse obvious placeholders (safe default)
    if grep -qE '^(JWT_SECRET|SESSION_SECRET|CSRF_SECRET|ADMIN_PASSWORD)=change-me$' "$file"; then
      echo "ERROR: .env.secrets contains placeholder secrets (change-me)."
      echo "Fix it, or delete .env.secrets and rerun this script to auto-generate safe secrets."
      return 1
    fi
    return 0
  fi

  echo "Generating .env.secrets with strong random values (local file; do not commit)."
  "$PY" - <<'PY'
import os, secrets
def rnd(n=32): return secrets.token_urlsafe(n)
lines = [
  "JWT_SECRET=" + rnd(48),
  "SESSION_SECRET=" + rnd(48),
  "CSRF_SECRET=" + rnd(48),
  "API_TOKEN=" + rnd(32),
  "ADMIN_USERNAME=admin",
  "ADMIN_PASSWORD=" + rnd(20),
]
with open(".env.secrets", "x", encoding="utf-8") as f:
  f.write("# Auto-generated by scripts/run_dev.sh (do not commit)\n")
  for ln in lines: f.write(ln + "\n")
print("Wrote .env.secrets")
PY

  echo ""
  echo "IMPORTANT: Admin bootstrap credentials were generated:"
  echo "- username: admin"
  echo "- password: (stored in .env.secrets)"
  echo "Open .env.secrets to view or change it."
  echo ""
}

echo "Golden Path (dev) — prerequisites"
need_cmd "$PY"
need_cmd ffmpeg
need_cmd ffprobe

# Config files
ensure_env_file ".env" ".env.example"
ensure_secrets_file

echo "Checking Python package import (install if needed)..."
if ! "$PY" -c "import dubbing_pipeline" >/dev/null 2>&1; then
  echo "ERROR: package import failed. Install from repo root:"
  echo "  python3 -m pip install -e ."
  exit 2
fi

export HOST="${HOST:-0.0.0.0}"
export PORT="${PORT:-8000}"
export REMOTE_ACCESS_MODE="${REMOTE_ACCESS_MODE:-tailscale}"
export COOKIE_SECURE="${COOKIE_SECURE:-0}"

echo ""
"$PY" scripts/show_config.py || true

LOCAL_URL="http://127.0.0.1:${PORT}/ui/login"
echo "URLs"
echo "----"
echo "- local (on this machine): $LOCAL_URL"
echo "- tailnet (on phone): run: $PY scripts/remote/tailscale_check.py"
echo ""
echo "Logs"
echo "----"
echo "- logs folder: ./logs/"
echo "- outputs:     ./Output/"
echo ""

echo "Starting web server (dev)..."
echo "Stop with Ctrl+C."
exec "$PY" -m dubbing_pipeline.web.run

