$ErrorActionPreference = "Stop"

# Golden Path (prod-ish): prefer Docker (api+redis), safe defaults.
# - Only port exposed: 8000 (HTTP) for tailnet access.
# - App enforces REMOTE_ACCESS_MODE=tailscale allowlist.

$Root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
Set-Location $Root

$env:PYTHONUNBUFFERED = "1"
$env:STRICT_SECRETS = "1"

function Require-Cmd($name) {
  $cmd = Get-Command $name -ErrorAction SilentlyContinue
  if (-not $cmd) {
    Write-Host "ERROR: missing prerequisite: $name"
    exit 1
  }
}

function Ensure-EnvFile($path, $template) {
  if (Test-Path $path) { return }
  if (Test-Path $template) {
    Copy-Item $template $path
    Write-Host "Created $path from $template"
    return
  }
  Write-Host "ERROR: missing $path (and template $template not found)"
  exit 1
}

function Ensure-SecretsFile {
  $path = ".env.secrets"
  if (Test-Path $path) {
    $txt = Get-Content $path -Raw
    if ($txt -match "^(JWT_SECRET|SESSION_SECRET|CSRF_SECRET|ADMIN_PASSWORD)=change-me$") {
      Write-Host "ERROR: .env.secrets contains placeholder secrets (change-me)."
      Write-Host "Fix it, or delete .env.secrets and rerun this script to auto-generate safe secrets."
      exit 1
    }
    return
  }

  Write-Host "Generating .env.secrets with strong random values (local file; do not commit)."
  python - <<'PY'
import secrets
def rnd(n=32): return secrets.token_urlsafe(n)
lines = [
  "JWT_SECRET=" + rnd(48),
  "SESSION_SECRET=" + rnd(48),
  "CSRF_SECRET=" + rnd(48),
  "API_TOKEN=" + rnd(32),
  "ADMIN_USERNAME=admin",
  "ADMIN_PASSWORD=" + rnd(20),
]
with open(".env.secrets", "x", encoding="utf-8") as f:
  f.write("# Auto-generated by scripts/run_prod.ps1 (do not commit)\n")
  for ln in lines: f.write(ln + "\n")
print("Wrote .env.secrets")
PY

  Write-Host ""
  Write-Host "IMPORTANT: Admin bootstrap credentials were generated:"
  Write-Host "- username: admin"
  Write-Host "- password: (stored in .env.secrets)"
  Write-Host "Open .env.secrets to view or change it."
  Write-Host ""
}

Write-Host "Golden Path (prod-ish) — prerequisites"
Require-Cmd "python"
Require-Cmd "docker"

Ensure-EnvFile ".env" ".env.example"
Ensure-SecretsFile

python scripts/show_config.py | Out-Host

Write-Host ""
Write-Host "Starting Docker services (api + internal redis)..."
Write-Host "Stop with: docker compose -f docker/compose.golden_path.tailscale.yml down"
docker compose -f docker/compose.golden_path.tailscale.yml up --build

