$ErrorActionPreference = "Stop"

# Golden Path (dev): local python run with safe defaults.
# - Enforces Tailscale allowlist mode.
# - Prints local + tailnet URL instructions.

$Root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
Set-Location $Root

$env:PYTHONUNBUFFERED = "1"
$env:STRICT_SECRETS = "1"

function Require-Cmd($name) {
  $cmd = Get-Command $name -ErrorAction SilentlyContinue
  if (-not $cmd) {
    Write-Host "ERROR: missing prerequisite: $name"
    exit 1
  }
}

function Ensure-EnvFile($path, $template) {
  if (Test-Path $path) { return }
  if (Test-Path $template) {
    Copy-Item $template $path
    Write-Host "Created $path from $template"
    return
  }
  Write-Host "ERROR: missing $path (and template $template not found)"
  exit 1
}

function Ensure-SecretsFile {
  $path = ".env.secrets"
  if (Test-Path $path) {
    $txt = Get-Content $path -Raw
    if ($txt -match "^(JWT_SECRET|SESSION_SECRET|CSRF_SECRET|ADMIN_PASSWORD)=change-me$") {
      Write-Host "ERROR: .env.secrets contains placeholder secrets (change-me)."
      Write-Host "Fix it, or delete .env.secrets and rerun this script to auto-generate safe secrets."
      exit 1
    }
    return
  }

  Write-Host "Generating .env.secrets with strong random values (local file; do not commit)."
  python - <<'PY'
import secrets
def rnd(n=32): return secrets.token_urlsafe(n)
lines = [
  "JWT_SECRET=" + rnd(48),
  "SESSION_SECRET=" + rnd(48),
  "CSRF_SECRET=" + rnd(48),
  "API_TOKEN=" + rnd(32),
  "ADMIN_USERNAME=admin",
  "ADMIN_PASSWORD=" + rnd(20),
]
with open(".env.secrets", "x", encoding="utf-8") as f:
  f.write("# Auto-generated by scripts/run_dev.ps1 (do not commit)\n")
  for ln in lines: f.write(ln + "\n")
print("Wrote .env.secrets")
PY

  Write-Host ""
  Write-Host "IMPORTANT: Admin bootstrap credentials were generated:"
  Write-Host "- username: admin"
  Write-Host "- password: (stored in .env.secrets)"
  Write-Host "Open .env.secrets to view or change it."
  Write-Host ""
}

Write-Host "Golden Path (dev) — prerequisites"
Require-Cmd "python"
Require-Cmd "ffmpeg"
Require-Cmd "ffprobe"

Ensure-EnvFile ".env" ".env.example"
Ensure-SecretsFile

Write-Host "Checking Python package import (install if needed)..."
python -c "import dubbing_pipeline" 2>$null
if ($LASTEXITCODE -ne 0) {
  Write-Host "ERROR: package import failed. Install from repo root:"
  Write-Host "  python -m pip install -e ."
  exit 2
}

if (-not $env:HOST) { $env:HOST = "0.0.0.0" }
if (-not $env:PORT) { $env:PORT = "8000" }
if (-not $env:REMOTE_ACCESS_MODE) { $env:REMOTE_ACCESS_MODE = "tailscale" }
if (-not $env:COOKIE_SECURE) { $env:COOKIE_SECURE = "0" }

python scripts/show_config.py | Out-Host

$localUrl = "http://127.0.0.1:$($env:PORT)/ui/login"
Write-Host ""
Write-Host "URLs"
Write-Host "----"
Write-Host "- local (on this machine): $localUrl"
Write-Host "- tailnet (on phone): run: python scripts/remote/tailscale_check.py"
Write-Host ""
Write-Host "Logs"
Write-Host "----"
Write-Host "- logs folder: .\logs\"
Write-Host "- outputs:     .\Output\"
Write-Host ""

Write-Host "Starting web server (dev)..."
Write-Host "Stop with Ctrl+C."
python -m dubbing_pipeline.web.run

